#!/bin/sh

# src: https://bglog.net/nachobrazovanie/post/%D0%9F%D0%B0%D0%BD%D0%B3%D1%80%D0%B0%D0%BC%D0%B0---%D0%B2%D1%81%D0%B8%D1%87%D0%BA%D0%B8-%D0%B1%D1%83%D0%BA%D0%B2%D0%B8-%D0%BE%D1%82-%D0%B0%D0%B7%D0%B1%D1%83%D0%BA%D0%B0%D1%82%D0%B0-%D0%B2-%D0%B5%D0%B4%D0%BD%D0%BE-%D0%B8%D0%B7%D1%80%D0%B5%D1%87%D0%B5%D0%BD%D0%B8%D0%B5#gsc.tab=0
# src: https://bglog.net/nachobrazovanie/post/Панграма---всички-букви-от-азбуката-в-едно-изречение#gsc.tab=0

echo "Вкъщи не яж сьомга с фиде без ракийка и хапка люта чушчица"
