#!/bin/sh
#old way: #!/usr/bin/bat -r5:


## sed -n '/^######/,$p' "$0" | sed '1d' | 



############################################################
1 monday
2 tuesday
3 wednesday
4 thursday
5 friday
6 saturday
7 sunday
8 monday























